### ISSUE TITLE
Support torch.compile

### ISSUE THREAD

**Issue by mobicham** [rhymes-ai/Aria#54]
We have an HQQ 4-bit version of the Aria model: https://github.com/mobiusml/hqq/blob/master/examples/hf/aria_multimodal.py
It's working great, but we need `torch.compile` support so it can run much faster. 

Any plan to support `torch.compile`? Basically it would require two changes:
- Switch from flash attn to scaled dot prod
- Use static cache instead of dynamic cache

These two changes should make the 4-bit model run significantly faster.

**Comment by xffxff** [comment]
@mobicham Thank you for the great work on quantizing the Aria model with HQQ!

I appreciate the detailed suggestion for optimizing with torch.compile. I’ll be dedicating some time to explore switching to scaled dot product attention and using a static cache. Will keep you posted on the progress!

**Comment by mobicham** [comment]
I think it will also require a few changes. For example, I noticed in the original implementation that some tensors are put on CPU in the Grouped GEMM forward pass, this will break CUDA Graphs. In general, it's better to keep all necessary tensors on the same GPU device to avoid issues with `torch.compile`.

Let me know if you face any issues, happy to help!

**Comment by xffxff** [comment]
> I think it will also require a few changes. For example, I noticed in the original implementation that some tensors are put on CPU in the Grouped GEMM forward pass, this will break CUDA Graphs. In general, it's better to keep all necessary tensors on the same GPU device to avoid issues with `torch.compile`.
> 
> Let me know if you face any issues, happy to help!

Thanks for pointing this out! Once I have full support for `torch.compile`, I'll be happy to address this issue and make necessary changes.

**Comment by xffxff** [comment]
@mobicham  I've added support for a static KV cache. However, for attention, only the language model supports `sdpa`, while the ViT (vision transformer) model does not. Currently, the behavior is as follows:

```python
AutoModelForCausalLM.from_pretrained(
    model_id_or_path, 
    device_map="auto", 
    torch_dtype=torch.bfloat16, 
    trust_remote_code=True, 
    attn_implementation="sdpa"
)
```

This configuration will apply `sdpa` to the language model without raising errors. For the ViT model, it will automatically fall back to using Flash Attention since `sdpa` is not supported there. Given that the ViT model only operates during the prefill phase, not supporting `sdpa` for it is acceptable.

I’ve pushed the latest updates to [Aria on Hugging Face](https://huggingface.co/rhymes-ai/Aria). Please try it out and let me know if you encounter any issues.

---

Regarding `torch.compile`, I experimented with optimizing the language model using:

```python
model.language_model.forward = torch.compile(model.language_model.forward)

with torch.inference_mode(), torch.cuda.amp.autocast(dtype=torch.bfloat16):
    with sdpa_kernel([SDPBackend.MATH]):
        output = model.generate(
            **inputs,
            max_new_tokens=500, 
            stop_strings=["<|im_end|>"],
            tokenizer=processor.tokenizer,
            do_sample=True,
            cache_implementation="static",
            temperature=0.9,
        )
```

Unfortunately, this did not yield any performance improvements. I suspect that the current implementations of `token_dispatcher` and `sequential_gemm` may not be well-suited for `torch.compile`. 

We might benefit from incorporating the optimizations used in the `gpt-fast` implementation
https://github.com/rhymes-ai/Aria/blob/b84e92876ea15caf53a83cc574805f4e7654d40b/gptfast/model.py#L300-L341

**Comment by mobicham** [comment]
Thanks a lot @xffxff ! 

- The vision language model doesn't need static cache. 
- Only the decoding phase should be compiled with a fixed batch-size.

I will play with it today and get back to you!

**Comment by mobicham** [comment]
Yeah I am also working on the meo inference part to make it compatible with torch.compile fullgraph! We need to avoid conditions and dynamic shapes.

**Comment by mobicham** [comment]
So here's a first version that doesn't break the graph (`mode='reduce-overhead', fullgraph=True`). 
I had to use a `custom_op` for the grouped-gemm because torch.compile was complaining about a couple of things that I wasn't able to fix unfortunately.
I don't see a large speed-up though vs. fp16, it should be 2-4x faster end-2-end.

https://gist.github.com/mobicham/66fe6bea89a8f7b8832256ec6b1ec74a

**Comment by mobicham** [comment]
Alright, made it! https://gist.github.com/mobicham/b1dc6af540e35eb4401b0a85b6fbe32e
It's about 4-6x faster and takes 3x less VRAM !

The current way to make it work is very hacky because `torch.compile` breaks with `input[start:end]`. I can get rid of the `custom_op` I think, which should make it slightly faster.

**Comment by xffxff** [comment]
> Alright, made it! https://gist.github.com/mobicham/b1dc6af540e35eb4401b0a85b6fbe32e It's about 4-6x faster and takes 3x less VRAM !

@mobicham  Just tried it out—super cool! Thanks again for all your hard work. I had been messing around with a few open-source quantization tools to quantize Aria before, but none of them helped with throughput. Your method made a huge difference!

**Comment by mobicham** [comment]
Thank you @xffxff !

**Comment by appoose** [comment]
Can we put an announcement about this online? Happy to coordinate.  

In a similar thread, do you have benchmarking code of your models somewhere. If so, happy to run accuracy scores with the quantized models and fp16 one.

**Comment by maazel-rhymes** [comment]
> Can we put an announcement about this online? Happy to coordinate.
> 
> In a similar thread, do you have benchmarking code of your models somewhere. If so, happy to run accuracy scores with the quantized models and fp16 one.

Hi appoose, 

I'm Maazel, Developer Relations team at Rhymes.ai. Thank you for your integration, amazing work! Yes we would love to have a joint announcement, and perhaps one step further-a tech blog, a more detailed intro guide (because many developers aren't that professional), and more...

And your Aana SDK product is cool, we wonder if you like Aria's performance and perhaps can replace Internlm+Blip2? If so, that would be another amazing use case we can both announce.

Yup evals can be complicated, we use our in-house eval framework and intend to keep that way. Perhaps some common public evals can be utilized?  (MMMU/WildVision/)

We can communicate details via **maazel@rhymes.ai** 
Best Regards

**Comment by xffxff** [comment]
@mobicham 
Try loading the model using the following code
```python
model = AutoModelForCausalLM.from_pretrained(
    model_id_or_path, 
    device_map="auto", 
    torch_dtype=torch.bfloat16, 
    trust_remote_code=True, 
    attn_implementation={
        "text_config": "sdpa", 
        "vision_config": "flash_attention_2"
    }
)
```

This issue might be related to recent changes in the `transformers`, as shown here:
https://github.com/huggingface/transformers/blob/1c471fc3070a9179f32d147df40b760804f2ef4e/src/transformers/modeling_utils.py#L1525-L1532

**Comment by mobicham** [comment]
Thanks! Cleaned up the code and made it a bit faster by getting rid of the `custom_op`: 
https://github.com/mobiusml/hqq/commit/f8c8dfef25ec7f5d1ca95b79ecba2604e7fc1a96
~1.7 secs vs. ~5.5 sec on the A100 SXM4 using ~16GB of VRAM
